[database]
type = "mysql"
host = "127.0.0.1"
port = 3306
name = "micro_imbd"
user = "user"
pass = "user"

[redis]
host = "localhost:6379"
pass = ""
db = "0"

[servers]

    [servers.gate]
    port = ":8080"

[services]

    [services.biz]
    prot = "tcp"
    port = ":8082"

    [services.auth]
    prot = "tcp"
    port = ":8083"

    [services.bookmark]
    prot = "tcp"
    port = ":8084"