version: '3.3'

services: 
  db:
    image: mysql/mysql-server
    environment: 
      MYSQL_DATABASE: 'micro_imbd'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: '123456'
    ports: 
      - '3306:3306'
    volumes: 
      - mysql_data:/data

volumes: 
  mysql_data: