version: "3.3"

services:
    db:
        image: mysql/mysql-server
        environment:
            MYSQL_DATABASE: "micro_imbd"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "user"
            MYSQL_ROOT_PASSWORD: "123456"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/data

    redis:
        image: "redis:latest"
        container_name: redis_imbd
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
